/**
 * COMPACT guide template (default `detail: 'compact'`).
 *
 * Sizing rationale (2026-09-23): the previous full template rendered ~19.5KB,
 * which clients offload to a file — the model then sees NOTHING and retry
 * loops followed (observed 47x + 25x). The compact template renders ~6-7KB,
 * i.e. 1-2 paged parts that always arrive inline.
 *
 * Content policy vs the full template:
 * - Tool routing table: "when to use" only — essential parameters live in the
 *   zod schemas every client receives via tools/list (see detail:'full').
 * - Stochastic algorithms: one line per operation.
 * - Workflow recipes: OUTSOURCED — fetch with section: 'recipes'.
 */

export const AGENTS_TEMPLATE_COMPACT = [
  '# Clear Thought — Reasoning Tool Guide for {{PROJECT_NAME}}',
  '',
  'Domain context: {{DOMAIN_CONTEXT}}. Codebase root: {{CODEBASE_ROOT}}.',
  '',
  'You have access to the **Clear Thought** MCP server: structured reasoning',
  'tools. This guide tells you which tool to use when and how to chain them.',
  '',
  '## Ground rules',
  '',
  '1. **Think before you act.** Start non-trivial tasks with',
  '   `sequential_thinking` to plan before using domain tools.',
  '2. **One reasoning step per tool call.** Feed each output into the next call.',
  '3. **Close what you open.** Iterative tools end with a `next*Needed` flag;',
  '   set it to `false` when done.',
  '4. **State lives server-side per session.** Stateful tools return a',
  '   `sessionContext` block with accumulated stats — read it, don\u2019t duplicate it.',
  '5. **Prefer the cheapest sufficient tool.** `mental_model` beats',
  '   `decision_framework` for lighter stakes.',
  '6. **Dual-mode tools** (`swot_analysis`, `mind_map`, `concept_map`,',
  '   `fishbone_diagram`, `issue_tree`, `premortem`, `fmea`, `fault_tree`,',
  '   `causal_graph`, `analogical_mapper`, `seven_seekers_orchestrator`,',
  '   `drag_point_audit` on empty logs) return a facilitation scaffold when you',
  '   provide no content. Answer the scaffold yourself and call again WITH the',
  '   content — never present a scaffold as a result.',
  '7. **swot_analysis specifics:** call with filled quadrants (plain strings or',
  '   `{text, impact 1-5, likelihood 1-5, tags[]}`) to get the TOWS analysis;',
  '   check `meta.truncatedPerQuadrant` before trusting completeness.',
  '',
  '## Calling conventions',
  '',
  'Every tool exists twice: as an individual tool (e.g. `mental_model`) and as',
  'an operation in a grouped toolset (`reasoning` with',
  '`operation: \u0027mental_model\u0027`). Identical parameters; toolset calls add the',
  '`operation` discriminator.',
  '',
  'Toolsets: `reasoning` (thinking, mental models, debugging, decisions,',
  'socratic, creative, systems, scientific, argumentation, argument_map,',
  'causal_graph, fermi, game_matrix) \u00b7 `visualization` (mind_map, concept_map,',
  'fishbone, swot, issue_tree) \u00b7 `utility` (analogical_mapper,',
  'assumption_xray, comparative_advantage, drag_point_audit,',
  'safe_struggle_designer, seven_seekers, value_of_information,',
  'existing_tool_example, setup_clearthought) \u00b7 `session` (session_info,',
  'session_export, session_import, session_save, session_load) \u00b7 `risk`',
  '(premortem, fmea, fault_tree) \u00b7 `workflow` (recipe_runner) \u00b7 `stochastic`',
  '(mdp, mcts, bandit, bayesian, hmm).',
  '',
  '## Tool routing (when to use what — parameters: see tool schemas)',
  '',
  '| Need | Tool |',
  '|---|---|',
  '| Plan / reason step by step | `sequential_thinking` |',
  '| Apply a thinking heuristic | `mental_model` (first_principles \\| opportunity_cost \\| error_propagation \\| rubber_duck \\| pareto_principle \\| occams_razor) |',
  '| Find a bug\u2019s root cause | `debugging_approach` |',
  '| Multi-persona deliberation | `collaborative_reasoning` |',
  '| Weighted decision | `decision_framework` |',
  '| Audit your reasoning quality | `metacognitive_monitoring` (run before high-stakes claims) |',
  '| Stress-test a claim with questions | `socratic_method` |',
  '| Generate creative options | `creative_thinking` |',
  '| Model system dynamics | `systems_thinking` |',
  '| Test a hypothesis empirically | `scientific_method` |',
  '| Build / attack an argument | `structured_argumentation`, `argument_map` (Toulmin completeness) |',
  '| Causation vs correlation | `causal_graph` |',
  '| Rough-estimate a quantity | `fermi_estimate` |',
  '| Strategic interaction | `game_matrix` |',
  '| Diagram of reasoning | `visual_reasoning` (individual tool only, not in a toolset) |',
  '| Hierarchical brainstorm | `mind_map` |',
  '| Relate concepts | `concept_map` |',
  '| Many-cause root-cause analysis | `fishbone_diagram` |',
  '| Strategic assessment | `swot_analysis` |',
  '| Decompose a problem | `issue_tree` |',
  '| Pre-mortem a plan | `premortem` |',
  '| Failure modes (RPN) | `fmea` |',
  '| Exact fault-tree probability | `fault_tree` (LAST gate = top gate) |',
  '| Import patterns from other domains | `analogical_mapper` |',
  '| Surface hidden assumptions | `assumption_xray` |',
  '| Assign tasks to best executor | `comparative_advantage` |',
  '| Find friction in a process log | `drag_point_audit` |',
  '| Deliberate-practice design | `safe_struggle_designer` |',
  '| Multi-lens research sweep | `seven_seekers_orchestrator` |',
  '| Is research worth it? | `value_of_information` |',
  '| Real stochastic computation | `stochasticalgorithm` |',
  '| Smoke-test wiring | `existing_tool_example` |',
  '| This guide as AGENTS.md | `setup_clearthought` |',
  '| Inspect / persist / restore session | `session_info` / `session_export` + `session_import` / `session_save` + `session_load` |',
  '| Guided multi-tool workflow | `recipe_runner` (debug-failure, architecture-decision, stress-test-conclusion, open-ended-ideation, multi-agent-delegation, long-research-question, decision-under-uncertainty) |',
  '',
  '## Stochastic algorithms (real, measured computation — validate your inputs)',
  '',
  '`mdp` sequential phase decisions \u00b7 `mcts` search environments \u00b7 `bandit`',
  'explore-vs-exploit with regret (runs persist per session via `runId`) \u00b7',
  '`bayesian` next best evaluation of expensive black-box functions \u00b7 `hmm`',
  'latent states behind observations (forward-backward \\| viterbi \\| both).',
  'Matrices must be row-stochastic (tol 1e-6); invalid inputs fail with the',
  'exact expected shape. Numbers are measured — no warranty about your model.',
  '',
  '## Session persistence',
  '',
  '1. Check state: `session_info` (also as resources: `clear-thought://session/stats` etc.).',
  '2. Before context ends/compacts: `session_export` → store in the project (e.g. `memory-bank/`), or `session_save` when the server has a `dataDir`.',
  '3. On resume: `session_import` / `session_load`, continue from the stats.',
  '',
  '## Workflow recipes — on demand',
  '',
  'Seven guided recipes exist (debug-failure, architecture-decision,',
  'stress-test-conclusion, open-ended-ideation, multi-agent-delegation,',
  'long-research-question, decision-under-uncertainty). They are NOT inlined',
  'here to keep this guide small. When you need the concrete tool chains,',
  'call `setup_clearthought` with the SAME arguments plus',
  '`section: \u0027recipes\u0027` (SHORT response), or browse them anytime via',
  '`recipe_runner` with `action: \u0027list\u0027`.',
  '',
  '## Anti-patterns',
  '',
  '- Never present a facilitation scaffold as an analysis result.',
  '- Never claim a root cause/decision without `metacognitive_monitoring` at high stakes.',
  '- Don\u2019t set `totalThoughts: 1` then issue 15 revisions — estimate honestly.',
  '- Don\u2019t interleave unfinished `sequential_thinking` branches without distinct `branchId`s.',
  '- Don\u2019t re-derive in prose what a tool already structured.',
  '',
  '## Project-specific conventions',
  '',
  '<!-- Customize this section per project. Example: -->',
  '',
  '- For trading decisions, always run `value_of_information` before requesting additional market data.',
  '- For refactors, `issue_tree` depth must not exceed 3.',
  '- Record the chosen option of every `decision_framework` run in `memory-bank/decisions.md`.',
].join('\n');

/**
 * Workflow recipes section, served on explicit request via
 * `section: 'recipes'`. Kept out of the compact template so the default
 * guide stays small; delivered as a SHORT standalone response.
 */
export const RECIPES_SECTION = [
  '## Workflow recipes (clear-thought)',
  '',
  'Each recipe: navigate with `recipe_runner` (start/advance), execute the',
  'recommended tools yourself per stage.',
  '',
  '1. **debug-failure:** `sequential_thinking` (plan, 3-5 thoughts) \u2192',
  '   `debugging_approach` (approachName matching the symptom class) \u2192',
  '   `fishbone_diagram` (only if multiple candidate causes) \u2192',
  '   `metacognitive_monitoring` before claiming the root cause.',
  '2. **architecture-decision:** `issue_tree` \u2192 `swot_analysis` per serious',
  '   option \u2192 `value_of_information` (research more? re-run swot) \u2192',
  '   `decision_framework` \u2192 optional `stochasticalgorithm` to quantify \u2192',
  '   `metacognitive_monitoring` before committing.',
  '3. **stress-test-conclusion:** `structured_argumentation` \u2192',
  '   `socratic_method` (clarification \u2192 assumptions \u2192 evidence) \u2192',
  '   `assumption_xray` on the weakest premise \u2192 revise, honest confidence.',
  '4. **open-ended-ideation:** `creative_thinking` (iterate) \u2192',
  '   `analogical_mapper` \u2192 `systems_thinking` on top ideas \u2192 `mind_map`.',
  '5. **multi-agent-delegation:** `comparative_advantage` \u2192 delegate \u2192',
  '   `drag_point_audit` on the process log \u2192 `safe_struggle_designer` if',
  '   skill-building is needed.',
  '6. **long-research-question:** `assumption_xray` on the question \u2192',
  '   `seven_seekers_orchestrator` (downstream_tools to refine) \u2192',
  '   `sequential_thinking` to synthesize \u2192 `session_export` to persist.',
  '7. **decision-under-uncertainty:** `value_of_information` \u2192',
  '   `decision_framework` \u2192 `stochasticalgorithm` (mdp/bayesian/mcts/bandit',
  '   per situation) \u2192 `metacognitive_monitoring` citing measured numbers AND',
  '   model assumptions.',
  '',
  'The server also exposes these as workflow prompts clients can render as',
  'ready-to-send starting messages.'
].join('\n');
