#!/bin/sh
# YARN-LOCK-TRAP guard: protects the yarn-managed repository root from the
# two recurring npm-side failure modes.
#
# 1. Lockfile format drift: npm does not read yarn.lock; an npm invocation
#    (npm ci/install at the root or in a member dir) can rewrite yarn.lock
#    into Yarn-v1 format ("# yarn lockfile v1" header), silently dropping the
#    Berry workspace entries. A staged yarn.lock must therefore look like a
#    Yarn-Berry lockfile: it carries the generator header and/or a top-level
#    "__metadata:" entry, and never the v1 header.
# 2. Root tree pruning: the same stale root package-lock.json can prune the
#    yarn-installed root node_modules (incident: typescript/.bin/tsc
#    disappeared, every workspace build failed with "tsc: not found").
#
# Exit codes: 0 = ok/skip, 1 = blocked (commit/push must not proceed).
# Remediation is always: git checkout -- yarn.lock && corepack yarn install.

set -u

fail() {
	printf '%s\n' "$@" >&2
	exit 1
}

# --- check 1: staged yarn.lock format ---------------------------------------
staged=$(git diff --cached --name-status -- yarn.lock 2>/dev/null)

case "$staged" in
D*)
	fail \
		"BLOCKED: yarn.lock is staged for deletion." \
		"The lockfile is the dependency source of truth (yarn Berry). Restore it:" \
		"  git checkout -- yarn.lock"
	;;
esac

if [ -n "$staged" ]; then
	staged_content=$(git show :yarn.lock 2>/dev/null)

	if printf '%s\n' "$staged_content" | grep -q '^# yarn lockfile v1'; then
		fail \
			"BLOCKED: staged yarn.lock is in Yarn-v1 format ('# yarn lockfile v1')." \
			"npm rewrote the yarn-managed lockfile (npm ignores yarn.lock)." \
			"Restore the Berry lockfile and reinstall with yarn:" \
			"  git checkout -- yarn.lock" \
			"  corepack yarn install"
	fi

	if ! printf '%s\n' "$staged_content" | grep -q '^__metadata:' &&
		! printf '%s\n' "$staged_content" | grep -q '^# This file is generated by running'; then
		fail \
			"BLOCKED: staged yarn.lock is not recognizable as a Yarn-Berry lockfile" \
			"(neither a '__metadata:' entry nor the yarn generator header found)." \
			"Restore the Berry lockfile and reinstall with yarn:" \
			"  git checkout -- yarn.lock" \
			"  corepack yarn install"
	fi
fi

# --- check 2: pruned root tree ----------------------------------------------
# Skip entirely on fresh clones (no node_modules yet): an absent tree is not
# a pruned tree. A tree missing the root devDependency binaries is exactly
# the post-npm-prune incident state.
if [ -d node_modules ] && [ ! -e node_modules/.bin/tsc ]; then
	fail \
		"BLOCKED: root node_modules looks pruned (node_modules/.bin/tsc missing" \
		"while typescript is a declared devDependency). An npm invocation has" \
		"likely replaced the yarn-installed tree. Repair with:" \
		"  corepack yarn install"
fi

exit 0
