#!/bin/sh
# YARN-LOCK-TRAP guard: protects the yarn-managed repository root from the
# two recurring npm-side failure modes.
#
# 1. Lockfile format drift: npm does not read yarn.lock; an npm invocation
#    (npm ci/install at the root or in a member dir) can rewrite yarn.lock
#    into Yarn-v1 format ("# yarn lockfile v1" header), silently dropping the
#    Berry workspace entries. A yarn.lock (staged copy, working tree, and —
#    at push time — the committed tip) must therefore look like a Yarn-Berry
#    lockfile: it carries the generator header and/or a top-level
#    "__metadata:" entry, and never the v1 header. The working-tree check
#    closes the `git add -N` + `git commit -a` bypass path, which no index-
#    based check can see.
# 2. Root tree pruning: the same stale root package-lock.json can prune the
#    yarn-installed root node_modules (incident: typescript/.bin/tsc
#    disappeared, every workspace build failed with "tsc: not found").
#
# Exit codes: 0 = ok/skip, 1 = blocked (commit/push must not proceed).
# Remediation is always: git checkout -- yarn.lock && corepack yarn install.
# The script fails CLOSED: if git state cannot be read, it blocks.

set -u

fail() {
	printf '%s\n' "$@" >&2
	exit 1
}

# Format check: reads the lockfile content on stdin, fails on v1 format or
# unrecognized (non-Berry) content.
check_format() {
	if printf '%s\n' "$1" | grep -q '^# yarn lockfile v1'; then
		fail \
			"BLOCKED: yarn.lock is in Yarn-v1 format ('# yarn lockfile v1')." \
			"npm rewrote the yarn-managed lockfile (npm ignores yarn.lock)." \
			"Restore the Berry lockfile and reinstall with yarn:" \
			"  git checkout -- yarn.lock" \
			"  corepack yarn install"
	fi
	if ! printf '%s\n' "$1" | grep -q '^__metadata:' &&
		! printf '%s\n' "$1" | grep -q '^# This file is generated by running'; then
		fail \
			"BLOCKED: yarn.lock is not recognizable as a Yarn-Berry lockfile" \
			"(neither a '__metadata:' entry nor the yarn generator header found)." \
			"Restore the Berry lockfile and reinstall with yarn:" \
			"  git checkout -- yarn.lock" \
			"  corepack yarn install"
	fi
}

# Always operate on the toplevel so manual invocation from a subdirectory
# validates the same files the hooks validate.
toplevel=$(git rev-parse --show-toplevel 2>/dev/null)
[ -n "$toplevel" ] || fail "BLOCKED: guard could not determine the repository toplevel."
cd "$toplevel" || exit 1

# --- check 1a: staged yarn.lock ----------------------------------------------
# Fail closed: an unreadable index must block, not skip.
staged=$(git diff --cached --name-status -- yarn.lock)
[ $? -eq 0 ] || fail "BLOCKED: guard could not read the git index."

case "$staged" in
D*)
	fail \
		"BLOCKED: yarn.lock is staged for deletion." \
		"The lockfile is the dependency source of truth (yarn Berry). Restore it:" \
		"  git checkout -- yarn.lock"
	;;
esac

if [ -n "$staged" ]; then
	staged_content=$(git show :yarn.lock 2>/dev/null)
	[ -n "$staged_content" ] || fail "BLOCKED: guard could not read the staged yarn.lock."
	check_format "$staged_content"
fi

# --- check 1b: working-tree yarn.lock ----------------------------------------
# Covers `git commit -a` / intent-to-add paths whose content never appears in
# the index before the pre-commit hook runs.
if [ -f yarn.lock ]; then
	worktree_content=$(cat yarn.lock)
	check_format "$worktree_content"
elif git cat-file -e HEAD:yarn.lock 2>/dev/null; then
	fail \
		"BLOCKED: yarn.lock is deleted in the working tree but tracked in HEAD." \
		"The lockfile is the dependency source of truth (yarn Berry). Restore it:" \
		"  git checkout -- yarn.lock"
fi

# --- check 1c: committed tip (effective at push time) ------------------------
# At pre-commit this re-checks HEAD (harmless); at pre-push it validates the
# tip being pushed, catching lockfile-drift commits made with --no-verify or
# from clones without core.hooksPath configured.
if git cat-file -e HEAD:yarn.lock 2>/dev/null; then
	head_content=$(git show HEAD:yarn.lock 2>/dev/null)
	[ -n "$head_content" ] || fail "BLOCKED: guard could not read HEAD:yarn.lock."
	check_format "$head_content"
fi

# --- check 2: pruned root tree ----------------------------------------------
# Skip entirely on fresh clones (no node_modules yet): an absent tree is not
# a pruned tree. A tree missing the root devDependency binaries is exactly
# the post-npm-prune incident state.
if [ -d node_modules ] && [ ! -e node_modules/.bin/tsc ]; then
	fail \
		"BLOCKED: root node_modules looks pruned (node_modules/.bin/tsc missing" \
		"while typescript is a declared devDependency). An npm invocation has" \
		"likely replaced the yarn-installed tree. Repair with:" \
		"  corepack yarn install"
fi

exit 0
