#!/bin/sh
# Test suite for scripts/check-yarn-lock.sh (YARN-LOCK-TRAP guard).
# Builds a throwaway git repo per case and asserts the guard's exit code.
# Usage: sh scripts/test-yarn-lock-guard.sh

set -u

GUARD=$(cd "$(dirname "$0")" && pwd)/check-yarn-lock.sh
pass=0
fail=0

expect_in() { # expect_in <dir> <name> <expected_exit> <command...>
	dir=$1
	name=$2
	want=$3
	shift 3
	if (cd "$dir" && "$@") >/dev/null 2>&1; then got=0; else got=$?; fi
	if [ "$got" -eq "$want" ]; then
		printf 'PASS %s\n' "$name"
		pass=$((pass + 1))
	else
		printf 'FAIL %s (expected exit %s, got %s)\n' "$name" "$want" "$got"
		fail=$((fail + 1))
	fi
}

BERRY='# This file is generated by running "yarn install" inside your project.
__metadata:
  version: 8
  cacheKey: 10'

V1='# yarn lockfile v1
'
# note: intentional v1 fixture (guard must reject this exact header)

new_repo() { # new_repo -> prints repo dir; berry lockfile committed; aborts on setup failure
	dir=$(mktemp -d)
	if ! (
		cd "$dir" &&
			git init -q . &&
			git config user.email t@t &&
			git config user.name t &&
			printf '%s\n' "$BERRY" > yarn.lock &&
			git add yarn.lock &&
			git commit -qm init
	) >/dev/null 2>&1; then
		printf 'FATAL: fixture setup failed in %s\n' "$dir" >&2
		exit 2
	fi
	printf '%s' "$dir"
}

# --- case 1: berry-format staged change passes ------------------------------
r=$(new_repo)
(
	cd "$r" &&
		printf '%s\nextra: line\n' "$BERRY" > yarn.lock &&
		git add yarn.lock
) >/dev/null 2>&1
expect_in "$r" "berry-change-pass" 0 sh "$GUARD"
rm -rf "$r"

# --- case 2: v1-format staged change blocks ---------------------------------
r=$(new_repo)
(
	cd "$r" &&
		printf '%s\n' "$V1" > yarn.lock &&
		git add yarn.lock
) >/dev/null 2>&1
expect_in "$r" "v1-change-block" 1 sh "$GUARD"
rm -rf "$r"

# --- case 2b: unrecognized format (no berry markers, no v1 header) blocks ---
r=$(new_repo)
(
	cd "$r" &&
		printf 'garbage content\n' > yarn.lock &&
		git add yarn.lock
) >/dev/null 2>&1
expect_in "$r" "unrecognized-format-block" 1 sh "$GUARD"
rm -rf "$r"

# --- case 3: staged deletion blocks -----------------------------------------
r=$(new_repo)
(cd "$r" && git rm -q yarn.lock) >/dev/null 2>&1
expect_in "$r" "deletion-block" 1 sh "$GUARD"
rm -rf "$r"

# --- case 4: unchanged yarn.lock skips (guard green on clean repo) ----------
r=$(new_repo)
expect_in "$r" "unchanged-skip" 0 sh "$GUARD"
rm -rf "$r"

# --- case 5: pruned tree blocks ---------------------------------------------
r=$(new_repo)
(cd "$r" && mkdir -p node_modules/.bin) >/dev/null 2>&1
expect_in "$r" "pruned-block" 1 sh "$GUARD"
rm -rf "$r"

# --- case 6: fresh clone (no node_modules) skips the prune check ------------
r=$(new_repo)
(
	cd "$r" &&
		printf '%s\nextra: line\n' "$BERRY" > yarn.lock &&
		git add yarn.lock
) >/dev/null 2>&1
test ! -d "$r/node_modules" || rm -rf "$r/node_modules"
expect_in "$r" "fresh-clone-skip" 0 sh "$GUARD"
rm -rf "$r"

# --- case 7: v1 in the WORKING TREE (unstaged) blocks -----------------------
# Covers the `git add -N` + `git commit -a` bypass path that no index-based
# check can see.
r=$(new_repo)
(cd "$r" && printf '%s\n' "$V1" > yarn.lock) >/dev/null 2>&1
expect_in "$r" "worktree-v1-unstaged-block" 1 sh "$GUARD"
rm -rf "$r"

# --- case 8: invocation from a subdirectory validates the root --------------
r=$(new_repo)
(
	cd "$r" &&
		mkdir -p servers/sub &&
		printf '%s\n' "$V1" > yarn.lock &&
		git add yarn.lock
) >/dev/null 2>&1
expect_in "$r/servers/sub" "subdir-invocation-block" 1 sh "$GUARD"
rm -rf "$r"

# --- case 9: unreadable git index fails CLOSED ------------------------------
r=$(new_repo)
expect_in "$r" "index-read-failure-block" 1 env GIT_INDEX_FILE=/nonexistent sh "$GUARD"
rm -rf "$r"

# --- case 10: committed v1 tip blocks (pre-push semantics) ------------------
# Simulates a drift commit made with --no-verify; the guard must reject the
# tip being pushed (HEAD:yarn.lock format check).
r=$(new_repo)
(
	cd "$r" &&
		printf '%s\n' "$V1" > yarn.lock &&
		git add yarn.lock &&
		git commit -qm trap --no-verify
) >/dev/null 2>&1
expect_in "$r" "committed-tip-block" 1 sh "$GUARD"
rm -rf "$r"

printf '\n%d passed, %d failed\n' "$pass" "$fail"
[ "$fail" -eq 0 ]
